apiVersion: v1
kind: Pod
metadata:
  name: memory-overcommit
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-ctr
    image: takytaky/stress
    resources:
      requests:
        memory: "1G"
      limits:
        memory: "4G"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "1.8G", "--vm-hang", "1"]
