apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-hostname-service
spec:
  type: LoadBalancer
  selector:
    app: hostname-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
