FROM centos:7
### ENV myName “Yu Mi”
# ENV myOrder Pizza Pasta Salad
# ENV myNumber 1004           
#
ENV myName="Yu Mi" \
    myOrder=Pizza\ Pasta\ Salad \
    myNumber=1004           



#CMD ["/bin/bash"] 
