apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-registry
  labels:
    app: secret-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-registry
  template:
    metadata:
      labels:
        app: secret-registry
    spec:
      containers:
      - name: testapp
        image: takytaky/app
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: secret-docker
