apiVersion: v1
kind: Pod
metadata:
  name: secret-file-pod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: secret-vol
      mountPath: "/secret"
  volumes:
  - name: secret-vol
    secret:
      secretName: secret-userpw
      items:
      - key: username
        path: my-group/my-username
        mode: 0400
