apiVersion: batch/v1
kind: Job
metadata:
  name: batch
spec:
  template:
    spec:
      containers:
      - name: batch
        image: takytaky/batch
      restartPolicy: Never
  backoffLimit: 4
  
#  parallelism: 4
#  completions: 4
