apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-container
    image: takytaky/app
    volumeMounts:
    - mountPath: /poddir
      name: hostpath-vol
    ports:
    - containerPort: 80
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /mnt
      type: Directory
